### 1. Simular Webhook de Pagamento (Liberar CPF)
POST http://localhost:3333/v1/onboarding/webhook-payment
Content-Type: application/json

{
  "cpf": "12345678901"
}

###

### 2. Simular Aluno Completando o Cadastro
POST http://localhost:3333/v1/onboarding/register
Content-Type: application/json

{
  "cpf": "12345678901",
  "name": "Aluno Arleu Tech",
  "email": "arleu@teste.com",
  "phone": "32999999999",
  "password": "senha_secreta_123"
}

###

### 3. Simular Aluno Fazendo Login Real
POST http://localhost:3333/v1/onboarding/sessions
Content-Type: application/json

{
  "email": "arleu@teste.com",
  "password": "senha_secreta_123"
}